### PR TITLE
 Encrypted heroku api key 

### PR DESCRIPTION
**Pull request by haoRchen**
Feature added so no contributor will leak their own API key to others. 
To use:

- Have the repo synced to Heroku and Travis CI command line clients installed.
- Retrieve the personal API key from Account Setting
- Enter : `travis encrypt $(heroku auth:token) --add deploy.api_key`
Travis will insert/replace the encrypted key into the .travis.yml file.

### CODE REVIEW

**Comment by Vimal-Raghubir** [comment]
Hao I am confused with the retrieving API key from Account Setting. And from my understanding I have to run the travis command before running node server.js everytime or just once?

**Comment by haoRchen** [comment]
You would only have to run the command once to ensure Travis can automatically deploy to Heroku when tests pass(commit the .yml file). However, you would need to run the command each time the API key gets updated. TravisCI needs the key for deployment to Heroku

**Comment by Vimal-Raghubir** [comment]
Ok thanks for the clarification Hao.

**Comment by SeanPrashad** [comment]
For future instances where you need to do this, is it possible to automatically call a script to run the command without the user knowing?

**Pull request merged**
